# This Makefile contains a single target that runs the program
#
# To use it, just run: make
#
# The make program will look for this makefile and compile your code
# as specified below.
#
# This makefile assumes you have only python3 installed

default: catPizzaReg.py
	@python catPizzaReg.py 0.22